### ISSUE TITLE
Classification guidance

### ISSUE THREAD

**Issue by jstumpin** [BarnyK/SkeletonActionClassification#1]
Could you provide a sample config for the above task as stated in the [example](https://github.com/BarnyK/SkeletonActionClassification/tree/master#classification)?

Thank you.

**Comment by BarnyK** [comment]
Hello
The configs are in the [configs/general/](https://github.com/BarnyK/SkeletonActionClassification/tree/master/configs/general) directory.
The most universal one is the [default.yaml](https://github.com/BarnyK/SkeletonActionClassification/blob/master/configs/general/prep_tests/default.yaml).
You will need to change some of the paths in there as they are non-relative.
Let me know if you need any more help.

**Comment by jstumpin** [comment]
Appreciate the prompt response. Here's where I'm at:

```
~/SkeletonActionClassification# python3 runner.py classify configs/general/prep_tests/default.yaml samples/digging.avi --model logs/j-xsub-120.pth
Loading YOLO model..
  0%|                                                   | 0/117 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/rapid/SkeletonActionClassification/runner.py", line 102, in <module>
    main()
  File "/home/rapid/SkeletonActionClassification/runner.py", line 94, in main
    handle_classify(args)
  File "/home/rapid/SkeletonActionClassification/procedures/single_file_classification.py", line 413, in handle_classify
    single_file_classification(args.video_file, cfg, args.model, args.save_file, args.method, args.window_save_file)
  File "/home/rapid/SkeletonActionClassification/procedures/single_file_classification.py", line 158, in single_file_classification
    model, norm_func = create_model_norm(cfg, device, model_path)
  File "/home/rapid/SkeletonActionClassification/procedures/single_file_classification.py", line 339, in create_model_norm
    num_classes = state_dict['net'][[x for x in state_dict['net'].keys()][-1]].shape[0]
KeyError: 'net'
100%|█████████████████████████████████████████| 117/117 [00:02<00:00, 55.87it/s]
```

Specifically stuck at [KeyError: 'net'](https://github.com/BarnyK/SkeletonActionClassification/blob/102d31cc0f0b2b1ca78bf67eb0c59cb83fede871/procedures/single_file_classification.py#L339). Got detector and pose estimator weights from [here](https://github.com/MVIG-SJTU/AlphaPose/issues/1162), STGCN++ action recognizer weights from [here](https://github.com/kennymckormick/pyskl/blob/main/configs/stgcn++/README.md), specifically the 120-XSub-Joint [model](http://download.openmmlab.com/mmaction/pyskl/ckpt/stgcnpp/stgcnpp_ntu120_xsub_hrnet/j.pth).

**Comment by BarnyK** [comment]
Unfortunately the model weights from the original ST-GCN++ repository are not compatible with my project.
I have modified the original code to remove the backbone + head split and merged them into a single model for better code clarity. I did't need the flexibility it provided so it seemed like a good idea at that time...
The architecture is the same but the keys in the state directories for the models are different.

The KeyError: 'net' is caused by the fact that I also store optimizer, scheduler, and normalization parameters in my model file.
So the program expects that the classification model weights will be under the "net" key in the dictionary.
This makes it much easier to resume training.

Some solutions: 
1. Easy
Retrain the model using my code. This will provide you with everything you need.
2. Easiest
I will upload the model files I have to Google drive [here](https://drive.google.com/drive/folders/1_ML8Oka0CmdbqiigL8g9uAnecOcKGP55?usp=drive_link).
You will be able to use those.
For now I only uploaded one model there. It has the the model file, config, and training log. 
The log will have the evaluation accuracy at the bottom.
It is best to use the pair of config and model files together.
3. Hard
In theory it is possible to adapt the orignal weights of ST-GCN++ to my model.
You would need to rename keys in the state dictionaries.
Sounds very messy and there is a high chance it will not work.

**Comment by jstumpin** [comment]
If that's the case, out of curiousity, what's the different between yours and [mmaction2](https://github.com/open-mmlab/mmaction2/tree/main/demo#long-video-demo)? Been testing on my scenes and found out skeleton-based works best (i.e. [stgcn/posec3d](https://github.com/open-mmlab/mmaction2?tab=readme-ov-file#-model-zoo-) using [long_skeleton_demo.py](https://github.com/open-mmlab/mmaction2/issues/2287) variant.

**Comment by BarnyK** [comment]
My project by no means is a competitor of mmaction2.
I wrote it because I needed an almost all-in-one solution for skeleton-based action classification using GCN.
And it is just that. It is much less complicated (I hope) than all the frameworks that want to support a big range of features.

**Comment by jstumpin** [comment]
> Unfortunately the model weights from the original ST-GCN++ repository are not compatible with my project. I have modified the original code to remove the backbone + head split and merged them into a single model for better code clarity. I did't need the flexibility it provided so it seemed like a good idea at that time... The architecture is the same but the keys in the state directories for the models are different.
> 
> The KeyError: 'net' is caused by the fact that I also store optimizer, scheduler, and normalization parameters in my model file. So the program expects that the classification model weights will be under the "net" key in the dictionary. This makes it much easier to resume training.
> 
> Some solutions:
> 
>     1. Easy
>        Retrain the model using my code. This will provide you with everything you need.
> 
>     2. Easiest
>        I will upload the model files I have to Google drive [here](https://drive.google.com/drive/folders/1_ML8Oka0CmdbqiigL8g9uAnecOcKGP55?usp=drive_link).
>        You will be able to use those.
>        For now I only uploaded one model there. It has the the model file, config, and training log.
>        The log will have the evaluation accuracy at the bottom.
>        It is best to use the pair of config and model files together.
> 
>     3. Hard
>        In theory it is possible to adapt the orignal weights of ST-GCN++ to my model.
>        You would need to rename keys in the state dictionaries.
>        Sounds very messy and there is a high chance it will not work.
> 
> 
> On a sidenote: In my project I mainly focused on classification using the pose estimated data. Most of other models mainly train and evaluate on data from kinect sensors. I found that models trained on kinect sensors perform worse on skeletons from pose estimation. Same can be said vice versa.

Yup, able to flawlessly run via solution #2 with **ntu120_xsub_100w_0** yielded the best outcome. Will need to reconsider other stuffs before considering solution #1. 

Thanks!

**Comment by BarnyK** [comment]
Good to know it worked.
Thank you for considering my project!
